# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoMessage.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InfoMessage(object):
    def setupUi(self, InfoMessage):
        InfoMessage.setObjectName("InfoMessage")
        InfoMessage.resize(709, 729)
        InfoMessage.setStyleSheet(".QMainWindow {\n"
"    min-width:709;\n"
"    min-height:729;\n"
"    max-width:709;\n"
"    max-height:729;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(InfoMessage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 520, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 450, 520, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 60, 701, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(0, 510, 701, 181))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.label_20 = QtWidgets.QLabel(self.widget1)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_21 = QtWidgets.QLabel(self.widget1)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.label_22 = QtWidgets.QLabel(self.widget1)
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_2.raise_()
        self.label_13.raise_()
        self.label_3.raise_()
        self.label_14.raise_()
        self.label_4.raise_()
        self.label_15.raise_()
        self.label_5.raise_()
        self.label_16.raise_()
        self.label_6.raise_()
        self.label_17.raise_()
        self.label_7.raise_()
        self.label_18.raise_()
        self.label_8.raise_()
        self.label_19.raise_()
        self.label_8.raise_()
        self.label_19.raise_()
        self.label_12.raise_()
        self.label_20.raise_()
        self.label_10.raise_()
        self.label_21.raise_()
        self.label_11.raise_()
        self.label_22.raise_()
        InfoMessage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InfoMessage)
        self.statusbar.setObjectName("statusbar")
        InfoMessage.setStatusBar(self.statusbar)

        self.retranslateUi(InfoMessage)
        QtCore.QMetaObject.connectSlotsByName(InfoMessage)

    def retranslateUi(self, InfoMessage):
        _translate = QtCore.QCoreApplication.translate
        InfoMessage.setWindowTitle(_translate("InfoMessage", "MainWindow"))
        self.label.setText(_translate("InfoMessage", "ОБЬЕКТ ПРОДАЖИ:"))
        self.label_9.setText(_translate("InfoMessage", "ПРОДАВЕЦ:"))
        self.label_2.setText(_translate("InfoMessage", "ID:"))
        self.label_3.setText(_translate("InfoMessage", "Адрес:"))
        self.label_4.setText(_translate("InfoMessage", "Площадь:"))
        self.label_5.setText(_translate("InfoMessage", "Кол-во комнат:"))
        self.label_6.setText(_translate("InfoMessage", "Тип сделки:"))
        self.label_7.setText(_translate("InfoMessage", "Цена:"))
        self.label_8.setText(_translate("InfoMessage", "Почтовый индекс:"))
        self.label_12.setText(_translate("InfoMessage", "Адрес:"))
        self.label_10.setText(_translate("InfoMessage", "ФИО:"))
        self.label_11.setText(_translate("InfoMessage", "Телефон:"))

